/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hashcode2020

import java.io.File
import java.util.*
import kotlin.collections.ArrayList

fun main(args: Array<String>) {
    println("Hello HashCode 2020!")

    val lines = ArrayList<String>()

    File("inputs/a_example.txt").forEachLine { lines.add(it) }
    val template = HashCodeTemplate(lines);
    val data = BookProblemData(template)

    val librairie = data.librairies.get(0)
    librairie.selectBook(0)
    val reponse = HashCodeReponse(Arrays.asList(1), librairie.serialize())
    reponse.toFile("Filename")

}

fun serializeLibrairies(librairies: List<Librairie>): List<List<String>> {
    return librairies.map { librairie -> librairie.serialize() }.flatMap { list -> list }
}